### ISSUE TITLE
How to construct the mapping relationship between images

### ISSUE THREAD

**Issue by CollapseEdge** [cogtoolslab/photo-sketch-correspondence#1]
Hello, I encountered some problems while reading your team's paper Learning Dense Correspondences between Photos and Sketches. I need your help. In the experimental part, you conducted a retrain comparative test on the two methods CNNGeo and WeakAlign. I can't understand how you construct the mapping relationship between images. CNNGeo is photo-photo, and your method is photo-sketch. I need to know how the training pairs are constructed during retraining.
![image](https://github.com/cogtoolslab/photo-sketch-correspondence/assets/123354572/284fb006-0664-495a-84a5-81708e34d21d)

**Comment by Charles-Lu** [comment]
Hi there!

Most methods in weakly-supervised correspondence learning (WeakAlign, NC-Net, DCCNet, PMD, and WarpC) take in paired images during training, which are not limited to photo-photo or photo-sketch pairs. We replaced the PF-Pascal dataset (photo-photo pairs) with our PSC dataset (photo-sketch pairs) during retraining.

(CNNGeo, on the other hand, operates on two augmented views of a single image. So it fails to find meaningful correspondences across modalities and has a worse performance in the retrain setting.)
