### ISSUE TITLE
Issues regarding dataset evaluation

### ISSUE THREAD

**Issue by CollapseEdge** [cogtoolslab/photo-sketch-correspondence#2]
Hello, I am attempting to conduct a transfer experiment using the PSC6K dataset you created. However, in the transfer experiment using the CATs++model, I did not obtain a very high PCK value. In terms of theoretical performance, CATs++performs better than CATs. May I ask if you have done any other operations on the images, such as Gaussian blur, during the evaluation experiment of the dataset. Or, could you provide some details about the transfer experiment.
![image](https://github.com/cogtoolslab/photo-sketch-correspondence/assets/123354572/1bb6d2e1-f8f2-43ce-8d52-fa48ee972764)
Thank you for your help.

**Comment by CollapseEdge** [comment]
The values in this picture were obtained from my transfer experiment using CATs++, I directly changed the datasets class of CATs++to support PSC6K datasets without doing any other operations

**Comment by Charles-Lu** [comment]
Hi there,

Thanks for reaching out. Yes, it seems that the PCK you obtained is lower than expected. We did not do any additional preprocessing to the sketches compared to the photos. In our transfer experiments, we simply replace the dataset/dataloader script in existing methods with ours. 

Could you share the edits you made to the original CAT++ repo?

**Comment by CollapseEdge** [comment]
Here is the code I have write: [dataset.zip](https://github.com/cogtoolslab/photo-sketch-correspondence/files/13594658/dataset.zip)
In this compressed package, there are three Python files, one is a newly derived PSC6K dataset class, and the other is the original datasets class. For some reasons, I have modified some of the original datasets content, and there is also a test. py file that adds a PSC6K option in the -- benchmark option

The following tree is the directory structure of my project
```
.
├── code
│   ├── data
│   │   ├── caltech.py
│   │   ├── dataset.py
│   │   ├── download.py
│   │   ├── keypoint_to_flow.py
│   │   ├── pfpascal.py
│   │   ├── pfwillow.py
│   │   ├── PSC6K.py
│   │   ├── __pycache__
│   │   └── spair.py
│   ├── environment.yml
│   ├── findpath.py
│   ├── images
│   │   ├── ARCH1.png
│   │   └── ARCH2.png
│   ├── models
│   │   ├── base
│   │   ├── cats_improved.py
│   │   ├── cats_model.py
│   │   ├── feature_backbones
│   │   ├── mod.py
│   │   └── __pycache__
│   ├── README.md
│   ├── test.py
│   ├── tmp
│   │   └── pycharm_project_370
│   ├── train.py
│   └── utils_training
│       ├── evaluation.py
│       ├── optimize.py
│       ├── __pycache__
│       └── utils.py
├── Datasets_CATs
│   ├── bench_mark
│   │   ├── alignment_dataset.py
│   │   ├── dataset_demo.ipynb
│   │   ├── examples.png
│   │   ├── photo_sketch_dataset.py
│   │   ├── README.md
│   │   ├── test_pairs_ps.csv
│   │   └── train_pairs_ps.csv
│   ├── __MACOSX
│   │   └── PF-dataset-PASCAL
│   ├── PF-dataset-PASCAL
│   │   └── test_pairs.csv
│   ├── PF-dataset-PASCAL.zip
│   ├── PF-PASCAL
│   │   ├── Annotations
│   │   ├── html
│   │   ├── index.html
│   │   ├── JPEGImages
│   │   ├── parsePascalVOC.mat
│   │   ├── ShowMatchingPairs
│   │   ├── test_pairs.csv
│   │   └── val_pairs.csv
│   ├── PSC6K
│   │   ├── test_pairs_ps.csv
│   │   └── test_pairs_st.csv
│   └── rendered_256x256
│       ├── 256x256
│       ├── test_pairs_ps.csv
│       └── test_pairs_st.csv
├── pre_weight
│   ├── pfpascal
│   │   ├── args.pkl
│   │   └── model_best.pth
│   ├── pfpascal_freeze
│   │   ├── args.pkl
│   │   └── model_best.pth
│   └── spair
│       ├── args.pkl
│       └── model_best.pth
├── rendered
└── tree.txt

30 directories, 46 files

```
Perhaps due to technical reasons, I may have made errors in the code. If you find that the indicator is low due to my own reasons, please provide correction. I would greatly appreciate it.

**Comment by Charles-Lu** [comment]
Hi there,

Sorry for getting back to you so late. I just got the chance to do some tests this week. The mistake you made is a little hard to spot  but simple:

In your file `dataset.py` line 218, you wrote:
```
x_crds = [x * (self.imside / org_imsize[0]) for x in pts_list[idx][0]]  
y_crds = [y * (self.imside / org_imsize[0]) for y in pts_list[idx][0]]
```
which should be 
```
x_crds = [x * (self.imside / org_imsize[0]) for x in pts_list[idx][0]]  
y_crds = [y * (self.imside / org_imsize[0]) for y in pts_list[idx][1]]
```
instead.

After the fix, the performance of CAT++ with `test_pairs_st.csv` and `pretrained weights on PF-PASCAL` increases to PCK@0.1=75.945 on my end (from PCK@0.1=46.822 in the image you shared). 

Hope this helps :)

**Comment by CollapseEdge** [comment]
Thank you very much for your help. I'm sorry for wasting your time because of this simple error. This problem has been solved.
